---
title: "Untitled"
author: "JJayes"
date: "17/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(readxl)
```

## Purpose

Group project for EKHM63 - Growth over space and time

### Reading in data

```{r}
df <- read_excel(here("data", "France.xlsx")) %>% 
  janitor::clean_names()
```

### Tidy to long format
```{r}
df <- df %>% 
  pivot_longer(-c(indicator, measure), names_to = "year") %>% 
  mutate(year = parse_number(year))
```

### Create labour productivity

```{r}
df_labour_prod <- df %>% 
  filter(indicator %in% c("GDP (volume)", "Total Hours")) %>% 
  select(indicator, year, value) %>% 
  pivot_wider(names_from = indicator) %>% 
  mutate(labour_productivity = `GDP (volume)` / `Total Hours`) %>% 
  select(year, labour_productivity)

df_labour_prod <- df_labour_prod %>% 
  mutate(indicator = "Labour Productivity",
         measure = "`GDP (volume)` / `Total Hours`") %>% 
  rename(value = labour_productivity)

df <- df %>% 
  bind_rows(df_labour_prod)
```



```{r}
df %>% 
  distinct(indicator)
```

### Calculate growth rates

```{r}
df <- df %>% 
  group_by(indicator) %>% 
  mutate(growth_rate = (value - lag(value))/lag(value)*100) %>% 
  ungroup()

df %>% 
  filter(str_detect(indicator, "Employment")) %>% 
  pivot_longer(cols = c(value, growth_rate)) %>% 
  ggplot(aes(year, value)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::number_format()) +
  facet_wrap(~ name, scales = "free_y", nrow = 2)
```

```{r}
tc <- 10

df_time_chunks <- df %>% 
  group_by(indicator) %>% 
  mutate(time_chunk = year - year %% tc) %>% 
  ungroup() %>% 
  group_by(indicator, time_chunk) %>% 
  mutate(index = row_number()) %>% 
  filter(index %in% c(1, tc)) %>% 
  mutate(ratio_value = value / lag(value),
         one_over_change_year = 1/(year - lag(year)),
         compound_gr = ratio_value^(one_over_change_year)-1) %>% 
  ungroup() 

df_time_chunks %>% 
  filter(str_detect(indicator, "Total Hours"),
         !is.na(compound_gr)) %>% 
  ggplot(aes(year, compound_gr)) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::percent_format())
```


GDP (volume), Total Hours, Capital Stock

```{r}
df_time_chunks %>% 
  filter(indicator %in% c("GDP (volume)", "Total Hours", "Capital Stock (K)"),
         !is.na(compound_gr)) %>% 
  ggplot(aes(year, compound_gr, colour = indicator)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 0, lty = 2) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(y = "Compound Growth Rate",
       x = NULL,
       colour = "Indicator")
```


```{r}
# capital weight
alpha <- .3
# labour weight
beta <- .7
```


```{r}

df_contribs <- df_time_chunks %>% 
  filter(indicator %in% c("GDP (volume)", "Total Hours", "Capital Stock (K)"),
         !is.na(compound_gr)) %>% 
  select(indicator, year, compound_gr) %>% 
  pivot_wider(names_from = indicator, values_from = compound_gr) %>% 
  mutate(capital_contrib = alpha*`Capital Stock (K)`,
         labour_contrib = beta*`Total Hours`,
         crude_tfp = `GDP (volume)` - capital_contrib - labour_contrib) %>% 
  pivot_longer(-year) %>% 
  filter(name %in% c("capital_contrib", "labour_contrib", "crude_tfp", "GDP (volume)")) %>% 
  mutate(name = str_to_sentence(str_replace(name, "_", " ")))

df_contribs %>% 
  pivot_wider(names_from = name) %>% 
  pivot_longer(-c(year, `Gdp (volume)`)) %>% 
  ggplot() +
  geom_col(aes(year, value, fill = name), 
           position = "dodge", 
           alpha = .8) +
  geom_point(aes(year, `Gdp (volume)`,colour = "GDP Growth")) +
  geom_line(aes(year, `Gdp (volume)`,colour = "GDP Growth")) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(x = NULL,
       fill = "Contribution to GDP Growth",
       colour = "Level of GDP Growth")
```



```{r}
df_time_chunks %>% 
  filter(indicator %in% c("GDP (volume)", "Total Hours", "Capital Stock (K)", "Labour Productivity"),
         !is.na(compound_gr)) %>% 
  select(indicator, year, compound_gr) %>% 
  pivot_wider(names_from = indicator, values_from = compound_gr) %>% 
  mutate(k_growth_per_worker = `Capital Stock (K)` - `Total Hours`,
         contrib_of_capital_deepening = k_growth_per_worker*alpha,
         crude_tfp = `Labour Productivity` - contrib_of_capital_deepening) %>% 
  pivot_longer(-year) %>% 
  filter(name %in% c("Labour Productivity",  "crude_tfp", "contrib_of_capital_deepening")) %>% 
  mutate(name = str_to_sentence(str_replace(name, "_", " "))) %>% 
  ggplot(aes(year, value, fill = name)) +
  geom_col(position = "dodge") +
  scale_y_continuous(labels = scales::percent_format())

```


