---
title: "italy_figures"
author: "JJayes"
date: "22/11/2021"
output: html_document
---

```{r}
library(tidyverse)
library(scales)
library(here)

theme_set(theme_light())
theme_update(
  legend.position = "bottom",
  text = element_text(size = 14),
  legend.text = element_text(size = 14),
  plot.caption = element_text(size = 12)
)
```

jpeg(filename = here("images", "italy_phones_mobiles_computers.jpeg"),
     height = 5,
     width = 8,
     units = "in",
     res = 1000)

## Initial figures

```{r}
df <- read_rds(here("data", "df_all_countries.rds")) %>% 
    filter(country == "Italy")
```

### Trends in GDP, labour, capital growth

```{r}
jpeg(filename = here("images", "italy_gdp_capital_hours_human_capital.jpeg"),
     height = 5,
     width = 8,
     units = "in",
     res = 1000)

df %>%
  # remove hk for first fig
  filter(indicator %in% c("GDP (volume)", "Capital Stock (K)", "Total Hours", "Human Capital Stock (HK)")) %>%
  group_by(indicator) %>%
  mutate(time_chunk = year - year %% 3) %>%
  ungroup() %>%
  group_by(indicator, time_chunk) %>%
  mutate(growth_rate = mean(growth_rate, na.rm = T)) %>%
  ungroup() %>%
  mutate(indicator = fct_relevel(indicator, "GDP (volume)", after = 0)) %>%
  ggplot(aes(time_chunk, growth_rate, colour = indicator)) +
  annotate("rect", xmin = 1964, xmax = 1977, ymin = -Inf, ymax = Inf, alpha = .5, fill = "grey80") +
  annotate("rect", xmin = 1990, xmax = 2005, ymin = -Inf, ymax = Inf, alpha = .5, fill = "grey80") +
  annotate("rect", xmin = 2006, xmax = 2018, ymin = -Inf, ymax = Inf, alpha = .5, fill = "grey80") +
  geom_point(size = 3) +
  geom_line() +
  geom_hline(yintercept = 0, lty = 2) +
  scale_y_continuous(labels = scales::percent_format(scale = 1, accuracy = 1)) +
  labs(
    x = NULL,
    y = "Growth rate",
    colour = NULL,
    title = "Evolution of GDP, Capital Stock and Hours Worked in Italy"
  ) +
  scale_color_brewer(palette = "Dark2")

dev.off()

```

### Timeline

```{r}
library(readxl)
library(ggrepel)
df <- read_excel(here("data", "italy_timeline.xlsx"))

jpeg(filename = here("images", "italy_timeline.jpeg"),
     height = 5,
     width = 8,
     units = "in",
     res = 1000)

df %>%
  ggplot(aes(year, y_position, colour = factor(group), label = event)) +
  annotate("rect", xmin = 1964, xmax = 1977, ymin = -Inf, ymax = Inf, alpha = .5, fill = "grey80") +
  annotate("rect", xmin = 1990, xmax = 2005, ymin = -Inf, ymax = Inf, alpha = .5, fill = "grey80") +
  annotate("rect", xmin = 2006, xmax = 2018, ymin = -Inf, ymax = Inf, alpha = .5, fill = "grey80") +
  annotate("text", x = c(1970, 1998, 2012), y = c(rep(1.7, 3)), label = c("Transition\nperiod", "Policy change\nperiod", "Stagnation\nperiod")) +
  geom_hline(yintercept = 0) +
  geom_point(aes(x = year, y = 0), size = 5) +
  geom_point(size = 3) +
  geom_segment(aes(y = y_position, yend = 0, xend = year)) +
  geom_label_repel() +
  scale_color_brewer(palette = "Dark2") +
  theme(
    axis.line.y = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks.y = element_blank(),
    # axis.text.x = element_blank(),
    # axis.ticks.x = element_blank(),
    # axis.line.x = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none"
  ) +
  labs(title = "Timeline")


dev.off()
```

## Italy other figs

```{r}
# library(readxl)
# 
# df <- read_excel(here("data", "italy_other_data.xlsx")) %>% janitor::clean_names()
# 
# df %>%
#   pivot_longer(-c(indicator_name, label)) %>%
#   mutate(name = parse_number(name)) %>%
#   rename(year = name) %>% write_rds(here("data", "italy_other_data.rds"))

df <- read_rds(here("data", "italy_other_data.rds"))
```

```{r}
# df_labs <- df %>% 
#   filter(label != "GDP growth",
#          !is.na(value)) %>% 
#   group_by(label) %>% 
#   filter(year == min(year))

jpeg(filename = here("images", "italy_other_data.jpeg"),
     height = 5,
     width = 8,
     units = "in",
     res = 1000)

df %>%
  filter(label != "GDP growth") %>%
  mutate(group = case_when(
    label %in% c("Inflation", "Unemployment") ~ "Macro trends",
    label %in% c("Female labour force participation", "Internet use") ~ "Internet and FLFP",
    TRUE ~ "Schooling"
  )) %>%
  mutate(group = fct_relevel(group, "Internet and FLFP", after = 2)) %>%
  ggplot(aes(year, value, colour = label)) +
  annotate("rect", xmin = 1964, xmax = 1977, ymin = -Inf, ymax = Inf, alpha = .5, fill = "grey80") +
  annotate("rect", xmin = 1990, xmax = 2005, ymin = -Inf, ymax = Inf, alpha = .5, fill = "grey80") +
  annotate("rect", xmin = 2006, xmax = 2018, ymin = -Inf, ymax = Inf, alpha = .5, fill = "grey80") +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::percent_format(scale = 1, accuracy = 1)) +
  scale_color_brewer(palette = "Dark2") +
  # geom_label(aes(label = label), data = df_labs) +
  facet_wrap(~group, nrow = 3, scales = "free_y") +
  theme(legend.position = "bottom") +
  labs(
    x = NULL,
    y = NULL,
    colour = NULL,
    title = "Time period characterisation for Italy"
  ) +
  guides(colour = guide_legend(nrow = 3))

dev.off()
```


### Tables over time

```{r}
range_function <- function(alpha, beta, year_1, year_2) {
  df %>%
    filter(
      # country == "France",
      year %in% c(year_1, year_2)
    ) %>%
    group_by(indicator) %>%
    mutate(
      ratio_value = value / lag(value),
      one_over_change_year = 1 / (year - lag(year)),
      compound_gr = (ratio_value^(one_over_change_year) - 1) * 100,
      range = paste0(year_1, "-", year_2)
    ) %>%
    ungroup() %>%
    select(indicator, year, value, country, compound_gr, range) %>%
    filter(!is.na(compound_gr)) %>%
    select(indicator, range, compound_gr) %>%
    pivot_wider(names_from = indicator, values_from = compound_gr) %>%
    janitor::clean_names() %>%
    mutate(
      capital_contribution = alpha * capital_stock_k,
      labour_contribution = beta * total_hours,
      contribution_of_human_capital = human_capital_stock_hk * beta,
      k_per_worker_growth = capital_stock_k - total_hours,
      contribution_of_capital_deepening = k_per_worker_growth * alpha,
      crude_tfp_via_labour_productivity = labour_productivity - contribution_of_capital_deepening,
      crude_tfp_via_gdp = gdp_volume - capital_contribution - labour_contribution,
      labour_augmented_tfp_via_gdp = crude_tfp_via_gdp - contribution_of_human_capital,
      labour_augmented_tfp_via_labour_productivity = crude_tfp_via_labour_productivity - contribution_of_human_capital
    ) %>%
    pivot_longer(-range)
}


df_range_1 <- range_function(.3, .7, 1964, 1977)
df_range_2 <- range_function(.3, .7, 1990, 2005)
df_range_3 <- range_function(.3, .7, 2006, 2018)

df_range <- df_range_1 %>% 
  bind_rows(df_range_2) %>% 
  bind_rows(df_range_3)
```

### Crude GDP 1

```{r}
colours <- c(
  "#EF5350FF",
  # red
  "#FFA726FF",
  # orange
  "#42A5F5FF",
  # blue
  "#26A69AFF"
  # teal
)

red_col <- "#EF5350FF"
orange_col <- "#FFA726FF"
blue_col <- "#42A5F5FF"
teal_col <- "#26A69AFF"
lime_col <- "#D4E157FF"
```


```{r}
jpeg(filename = here("images", "italy_crude_tfp_1.jpeg"),
     height = 8,
     width = 8,
     units = "in",
     res = 1000)

df_range %>%
  filter(name %in% c("capital_contribution", "labour_contribution", "crude_tfp_via_gdp", "gdp_volume")) %>%
  pivot_wider(names_from = name) %>%
  pivot_longer(-c(range, gdp_volume)) %>%
  mutate(name = str_to_title(str_replace_all(name, "_", " "))) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  geom_col(aes(range, value, fill = name), alpha = .9) +
  geom_point(aes(range, gdp_volume, colour = "GDP Growth"), size = 5) +
  scale_fill_manual(values = c(orange_col, teal_col, blue_col)) +
  scale_color_manual(values = red_col) +
  guides(fill = guide_legend(nrow = 2, byrow = T)) +
  # geom_line(aes(as.numeric(range), gdp_volume, colour = "GDP Growth")) +
  labs(
    x = NULL,
    y = "GDP growth rate\n contribution to growth",
    colour = NULL,
    fill = NULL
  )

dev.off()
```

```{r}
library(gt)
library(paletteer)

df_range %>%
  filter(name %in% c("capital_contribution", "labour_contribution", "crude_tfp_via_gdp", "gdp_volume")) %>%
  pivot_wider(names_from = name) %>%
  gt() %>%
  fmt_number(columns = -range) %>%
  data_color(
    columns = gdp_volume,
    colors = scales::col_numeric(
      # red
      palette = as.character(paletteer_d("ggsci::red_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = capital_contribution,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::orange_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = labour_contribution,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::blue_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = crude_tfp_via_gdp,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::teal_material", n = 6)),
      domain = NULL
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "left",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_body(
        columns = gdp_volume
      )
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "bottom",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_column_labels(
        columns = gt::everything()
      )
    )
  ) %>%
  cols_label(
    range = "Period",
    gdp_volume = "GDP Growth",
    capital_contribution = "Capital Contribution",
    labour_contribution = "Labour Contribution",
    crude_tfp_via_gdp = "Crude TFP"
  ) %>% gtsave(filename = here("tables", "human_capital_1_v1.PNG"))
```

### Crude TFP by labour productivity

```{r}

jpeg(filename = here("images", "italy_crude_tfp_2.jpeg"),
     height = 8,
     width = 8,
     units = "in",
     res = 1000)

df_range %>%
  filter(name %in% c("labour_productivity", "contribution_of_capital_deepening", "crude_tfp_via_labour_productivity")) %>%
  pivot_wider(names_from = name) %>%
  pivot_longer(-c(range, labour_productivity)) %>%
  mutate(name = str_to_title(str_replace_all(name, "_", " "))) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  geom_col(aes(range, value, fill = name), alpha = .9) +
  geom_point(aes(range, labour_productivity, colour = "Labour Productivity"), size = 5) +
  scale_fill_manual(values = c(orange_col, teal_col, blue_col)) +
  scale_color_manual(values = red_col) +
  guides(fill = guide_legend(nrow = 2, byrow = T)) +
  # geom_line(aes(as.numeric(range), gdp_volume, colour = "GDP Growth")) +
  labs(
    x = NULL,
    y = "GDP growth rate\n contribution to growth",
    colour = NULL,
    fill = NULL
  )

dev.off()
```

```{r}
df_range %>%
  filter(name %in% c("contribution_of_capital_deepening", "labour_productivity", "crude_tfp_via_labour_productivity")) %>%
  pivot_wider(names_from = name) %>%
  gt() %>%
  fmt_number(columns = -range) %>%
  data_color(
    columns = labour_productivity,
    colors = scales::col_numeric(
      # red
      palette = as.character(paletteer_d("ggsci::red_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = contribution_of_capital_deepening,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::orange_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = crude_tfp_via_labour_productivity,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::teal_material", n = 6)),
      domain = NULL
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "left",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_body(
        columns = labour_productivity
      )
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "bottom",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_column_labels(
        columns = gt::everything()
      )
    )
  ) %>% 
  cols_label(
    range = "Period",
    # gdp_volume = "GDP Growth",
    labour_productivity = "Labour Productivity",
    contribution_of_capital_deepening = "Contribution of Capital Deepening",
    crude_tfp_via_labour_productivity = "Crude TFP"
  ) 
# %>% gtsave(filename = here("tables", "crude_tfp_2_v1.PNG"))
```

#### Comparing

```{r}
domain_2 = c(-1, 4)

df_range %>%
  filter(name %in% c("crude_tfp_via_labour_productivity", "crude_tfp_via_gdp")) %>%
  mutate(value = round(value, 2)) %>% 
  pivot_wider(names_from = range) %>%
  mutate(name = str_to_title(str_replace_all(name, "_", " "))) %>%
  gt() %>%
  fmt_number(-name) %>%
  cols_label(
    name = " "
  ) %>%
  data_color(
    columns = 2,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::purple_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = 3,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::indigo_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = 4,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::cyan_material", n = 6)),
      domain = NULL
    )
  ) 
  # gtsave(filename = here("tables", "crude_tfp_comparison_1_v1.PNG"))
  
```


### Human capital via GDP

```{r}

jpeg(filename = here("images", "italy_labour_augmented_tfp_1.jpeg"),
     height = 8,
     width = 8,
     units = "in",
     res = 1000)


df_range %>%
  filter(name %in% c("gdp_volume", "capital_contribution", "labour_contribution", "contribution_of_human_capital", "labour_augmented_tfp_via_gdp")) %>%
  pivot_wider(names_from = name) %>%
  pivot_longer(-c(range, gdp_volume)) %>%
  mutate(name = str_to_title(str_replace_all(name, "_", " "))) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  geom_col(aes(range, value, fill = name), alpha = .9) +
  geom_point(aes(range, gdp_volume, colour = "GDP Growth"), size = 5) +
  scale_fill_manual(values = c(orange_col, lime_col, teal_col, blue_col)) +
  scale_color_manual(values = red_col) +
  guides(fill = guide_legend(nrow = 2, byrow = T)) +
  labs(
    x = NULL,
    y = "GDP growth rate\n contribution to growth",
    colour = NULL,
    fill = NULL
  )

dev.off()
```

```{r}
df_range %>%
  filter(name %in% c("gdp_volume", "capital_contribution", "labour_contribution", "contribution_of_human_capital", "labour_augmented_tfp_via_gdp")) %>%
  pivot_wider(names_from = name) %>%
  gt() %>%
  fmt_number(columns = -range) %>%
  data_color(
    columns = gdp_volume,
    colors = scales::col_numeric(
      # red
      palette = as.character(paletteer_d("ggsci::red_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = capital_contribution,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::orange_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = labour_contribution,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::blue_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = contribution_of_human_capital,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::lime_material", n = 6)),
      domain = NULL
    )
  ) %>%
    data_color(
    columns = labour_augmented_tfp_via_gdp,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::teal_material", n = 6)),
      domain = NULL
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "left",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_body(
        columns = gdp_volume
      )
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "bottom",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_column_labels(
        columns = gt::everything()
      )
    )
  ) %>% 
  cols_label(
    range = "Period",
    gdp_volume = "GDP Growth",
    capital_contribution = "Capital",
    labour_contribution = "Labour",
    contribution_of_human_capital = "Human Capital",
    labour_augmented_tfp_via_gdp = "LA TFP"
  ) 
# %>% gtsave(filename = here("tables", "la_tfp_1_v1.PNG"))


```

### Human capital via Labour Productivtiy

```{r}
jpeg(filename = here("images", "italy_labour_augmented_tfp_2.jpeg"),
     height = 8,
     width = 8,
     units = "in",
     res = 1000)


df_range %>%
  filter(name %in% c("labour_productivity", "contribution_of_capital_deepening", "contribution_of_human_capital", "labour_augmented_tfp_via_labour_productivity")) %>%
  pivot_wider(names_from = name) %>%
  pivot_longer(-c(range, labour_productivity)) %>%
  mutate(name = str_to_title(str_replace_all(name, "_", " "))) %>%
  ggplot() +
  geom_hline(yintercept = 0, lty = 2) +
  geom_col(aes(range, value, fill = name), alpha = .9) +
  geom_point(aes(range, labour_productivity, colour = "Labour Productivity"), size = 5) +
  scale_fill_manual(values = c(orange_col, blue_col, teal_col)) +
  scale_color_manual(values = red_col) +
  guides(fill = guide_legend(nrow = 3, byrow = T)) +
  # geom_line(aes(as.numeric(range), gdp_volume, colour = "GDP Growth")) +
  labs(
    x = NULL,
    y = "GDP growth rate\n contribution to growth",
    colour = NULL,
    fill = NULL
  )

dev.off()
```

```{r}
df_range %>%
  filter(name %in% c("labour_productivity", "contribution_of_capital_deepening", "contribution_of_human_capital", "labour_augmented_tfp_via_labour_productivity")) %>%
  pivot_wider(names_from = name) %>%
  gt() %>%
  fmt_number(columns = -range) %>%
  data_color(
    columns = labour_productivity,
    colors = scales::col_numeric(
      # red
      palette = as.character(paletteer_d("ggsci::red_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = contribution_of_capital_deepening,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::orange_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = contribution_of_human_capital,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::blue_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = labour_augmented_tfp_via_labour_productivity,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::teal_material", n = 6)),
      domain = NULL
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "left",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_body(
        columns = labour_productivity
      )
    )
  ) %>%
  tab_style(
    style = list(
      cell_borders(
        sides = "bottom",
        color = "black",
        weight = px(3)
      )
    ),
    locations = list(
      cells_column_labels(
        columns = gt::everything()
      )
    )
  ) %>% 
  cols_label(
    range = "Period",
    labour_productivity = "Labour Productivity",
    contribution_of_capital_deepening = "Capital Deepening",
    contribution_of_human_capital = "Human Capital",
    labour_augmented_tfp_via_labour_productivity = "LA TFP"
  )
# %>% gtsave(filename = here("tables", "la_tfp_2_v1.PNG"))


```



### Comparison 2

```{r}
labour_augmented_tfp_via_gdp

domain_2 = c(-1, 4)

df_range %>%
  filter(name %in% c("crude_tfp_via_labour_productivity", "crude_tfp_via_gdp", "labour_augmented_tfp_via_gdp", "labour_augmented_tfp_via_labour_productivity")) %>%
  pivot_wider(names_from = range) %>%
  mutate(name = str_to_title(str_replace_all(name, "_", " "))) %>%
  gt() %>%
  fmt_number(-name) %>%
  cols_label(
    name = " "
  ) %>%
  data_color(
    columns = 2,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::purple_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = 3,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::indigo_material", n = 6)),
      domain = NULL
    )
  ) %>%
  data_color(
    columns = 4,
    colors = scales::col_numeric(
      palette = as.character(paletteer_d("ggsci::cyan_material", n = 6)),
      domain = NULL
    )
  ) 
# %>% gtsave(filename = here("tables", "tfp_comparison_2_v1.PNG"))
```

